# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 07:18
from __future__ import unicode_literals

import designer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
                ('card_brand', models.CharField(max_length=20)),
                ('card_last4', models.CharField(max_length=5)),
                ('card_exp_month', models.CharField(max_length=5)),
                ('card_exp_year', models.CharField(max_length=5)),
                ('next_payment', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('failed_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('period_ending', models.DateTimeField()),
                ('paid', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('long_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=designer.models.profile_media_upload_location)),
                ('website', models.URLField(blank=True, max_length=50, null=True)),
                ('data', models.IntegerField(default=0)),
                ('data_cap', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('view_profile', 'Can see all profile info'), ('edit_profile', 'Can edit any profile info'), ('profile_admin', 'Can change settings for a profile')),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('public', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=designer.models.repo_media_upload_location)),
                ('created_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('head_sha1', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'permissions': (('view_project', 'Can see all project info'), ('edit_project', 'Can update project content'), ('repo_project', 'Can change admin settings for a project')),
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('beta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='designer.Profile')),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('designer.profile',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='designer.Profile')),
                ('public_name', models.CharField(blank=True, max_length=50, null=True)),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            bases=('designer.profile',),
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to='designer.Profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designer.License'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_repo_in_repo', to='designer.Project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designer.SubPlan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.SubPlan'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to='designer.TeamProfile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='team_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.TeamProfile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'creator')]),
        ),
    ]
