# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_auto_20161014_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'Can see all project info'), ('edit_project', 'Can update project content'), ('repo_project', 'Can change admin settings for a project'))},
        ),
        migrations.AlterField(
            model_name='license',
            name='long_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='license',
            name='short_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designer.Plan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designer.License'),
        ),
    ]
