# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_auto_20161014_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
